### PR TITLE
stringifyDomainPattern utility unit tests and bug fixes

### LINKED ISSUE #12: Write unit tests for untested utilities
There are a lot of useful functions in cross-domain-utils, but they aren't all tested! Write some unit tests for untested utilities. 

To find what's missing, run `npm test`, then `open coverage/index.html` to see what files are missing tests.

### PR DESCRIPTION
**Pull request by Abdul-Sen**
#12 . Hi, I wrote some tests for the `stringifyDomainPattern` utility and fixed some bugs that my unit tests came across in the function. 
There were 2 minor changes made to the utility function and the reasons for those changes are listed below :

## Change # 1

Initially my `should stringify a single regex expression to RegExp` test was failing with the following error:

Screenshot-from-2020-10-03-19-20-22

I fixed this issue by simply adding a `)` in the return string to `stringifyDomainPattern` function in `src/utils.js ` that seemed to be missing because of a typo which then ran my unit test successfully:

Screenshot-from-2020-10-03-19-25-28

## Change # 2

I noticed that the function also accepts array of regex patterns but the return was without `RegExp` but still had parentheses which indicated that the `RegExp` function missing was a mistake. It also made for inconsistant string returns. This then caused my test `should stringify an array of domain patterns to RegExp` to break with the folowing output: 

Screenshot-from-2020-10-03-21-36-58

I simply added `RegExp` to the return string and that change made my test succeed

Screenshot-from-2020-10-03-21-38-32

Please let me know if anything needs to be reverted or if there is something else you'd like me to do to meet the merge requirements.

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -868,9 +868,9 @@ export function matchDomain(pattern : DomainMatcher, origin : DomainMatcher) : b
 
 export function stringifyDomainPattern(pattern : DomainMatcher) : string {
     if (Array.isArray(pattern)) {
-        return `(${ pattern.join(' | ') })`;
+        return `RegExp(${ pattern.join(' | ') })`;
```
Comment (bluepnume) [inline src/utils.js]: According to the `DomainMatcher` type, if `pattern` is an array, it's an array of strings.

**Comment by bluepnume** [comment]
Thanks for taking this up! Added one small comment.

**Comment by Abdul-Sen** [comment]
Hey can i close this PR and continue to add new unit tests for other utilities under the same issue but with different PRs? I apologize I am still fairly to open source contributions.

**Comment by bluepnume** [comment]
Hi @Abdul-Sen -- why not keep this open, and make other PRs from different branches? You can make multiple PRs to the same repo, from different branches, and keep them separate that way.

If you can fix the array-of-strings case, I'd be happy to merge this PR in 👍

File: src/utils.js (hunk 1 above)
Comment (bluepnume) [reply src/utils.js]: (So I think we should just keep this as `(${ pattern.join(' | ') })`)

**Review by bluepnume — APPROVED** [review]
Looks great!
